tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('update_task/<str:pk>/', views.updateTask, name='update_task'),
    path('delete_task/<str:pk>/', views.deleteTask, name='delete'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
]

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from django.forms import ModelForm
from . models import *


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from .models import *


def index(request):
    tasks = Task.objects.all()

    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("tasks:index")

    context = {'tasks': tasks, 'form': form}

    return render(request, 'tasks/list.html', context)


def updateTask(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("tasks:index")

    context = {'form': form, 'task':task}

    return render(request, 'tasks/update_task.html', context)


def deleteTask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect("tasks:index")

    context = {'item': item}
    return render(request, 'tasks/delete.html', context)

tasks/templates/tasks/delete.html
{% extends 'tasks/list.html' %}
{% block content %}
<h3>Are you sure you want to delete "{{item}}"</h3>
<a href="{% url 'tasks:index' %}">Cancel</a>

<form method="POST" action="{% url 'tasks:delete' item.id %}">
    {% csrf_token %}
    <input type="submit" name="Confirm">
</form>

{% endblock content %}

tasks/templates/tasks/list.html
{% load static %}
{% load widget_tweaks %}
<! DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do List App</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="container">
    <div class="todo-app">
        <h2>To-Do List <img src="{% static 'images/icon.png' %}" alt="notepad"></h2>
        {% block content %}
            <form method="post" action="{% url 'tasks:index' %}">
                <div class="row">
                    {% csrf_token %}
                    {% render_field form.title placeholder="Add your text" class+="form-control" style="flex: 1; border: none; outline: none; background: transparent; padding: 10px; font-size: 14px;" %}
                    <button type="submit">Add</button>
                </div>

                <ul id="list-container">
                {% for task in tasks %}
                    <li>
                    {% if task.complete == True %}
                        <strike><span class="task-text">{{task}}</span></strike>
                    {% else %}
                        <span class="task-text">{{task}}</span>
                    {% endif %}

                    <a href="{% url 'tasks:update_task' task.id %}" class="update-link">Update</a>
                    <a href="{% url 'tasks:delete' task.id %}" class="delete-link">Delete</a>
                    </li>
                {% endfor %}
                </ul>


            </form>

        {% endblock content %}
    </div>


</div>
</body>


</html>

tasks/templates/tasks/update_task.html
{% extends 'tasks/list.html'  %}
{% block content %}
<h3>Updated Task</h3>

<form method="post" action="{% url 'tasks:update_task' task.id%}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Update Task">
</form>

{% endblock content %}